// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBI7GnTjOuvamPrA1aQyEFGfmTXb8OG35o',
    appId: '1:792779153878:web:efd044ac3b57075080c477',
    messagingSenderId: '792779153878',
    projectId: 'eventbridge-d9fd4',
    authDomain: 'eventbridge-d9fd4.firebaseapp.com',
    storageBucket: 'eventbridge-d9fd4.firebasestorage.app',
    measurementId: 'G-6GGZGNSC05',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3PfdAbPSGlkZZtIFi8LaaWedwu9NaqsM',
    appId: '1:792779153878:android:b4a33c5a3aff7cda80c477',
    messagingSenderId: '792779153878',
    projectId: 'eventbridge-d9fd4',
    storageBucket: 'eventbridge-d9fd4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvXe1Px7XxeCqzlqwmHvZ1w5UBkETGtaE',
    appId: '1:792779153878:ios:4548cf7e4f6b252f80c477',
    messagingSenderId: '792779153878',
    projectId: 'eventbridge-d9fd4',
    storageBucket: 'eventbridge-d9fd4.firebasestorage.app',
    iosBundleId: 'com.example.eventbridge1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvXe1Px7XxeCqzlqwmHvZ1w5UBkETGtaE',
    appId: '1:792779153878:ios:4548cf7e4f6b252f80c477',
    messagingSenderId: '792779153878',
    projectId: 'eventbridge-d9fd4',
    storageBucket: 'eventbridge-d9fd4.firebasestorage.app',
    iosBundleId: 'com.example.eventbridge1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBI7GnTjOuvamPrA1aQyEFGfmTXb8OG35o',
    appId: '1:792779153878:web:bb91775c219fe7b780c477',
    messagingSenderId: '792779153878',
    projectId: 'eventbridge-d9fd4',
    authDomain: 'eventbridge-d9fd4.firebaseapp.com',
    storageBucket: 'eventbridge-d9fd4.firebasestorage.app',
    measurementId: 'G-EKVNT30VMW',
  );
}
